# Generated by Django 3.2.19 on 2023-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='media/avatar.png', upload_to='media/images/'),
        ),
    ]
